# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "RnCICD.xcodeproj")
#     build_app(workspace: "RnCICD.xcworkspace", scheme: "RnCICD")
#     upload_to_testflight
#   end
# end

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Sync certificates and provisioning profiles using match
    match(
      type: "appstore",            # For App Store distribution
      readonly: false              # Allow Fastlane to create new profiles if needed
    )
    
    # Increment the build number
    increment_build_number(
      xcodeproj: "RnCICD.xcodeproj"
    )
    
    # Build the app using the Release configuration
    build_app(
      workspace: "RnCICD.xcworkspace",
      scheme: "RnCICD",
      export_method: "app-store"   # Ensure it's set for App Store/TestFlight distribution
    )
    
    # Upload the build to TestFlight
    upload_to_testflight
  end
end
